DECLARE @FCY VARCHAR(3);
SET @FCY = 'AE1';

SELECT 
ITM.ITMREF_0,
ITMDES1_0,
TCLCOD_0,
XFECOD_0,
BPS.BPSNUM_0,
BPS.BPSNAM_0,
ITM.PUU_0,
ITMBPS.ITMREFBPS_0,
ITF.REOMINQTY_0,
ITF.MFGLOTQTY_0,
ITM.OFS_0,
ITF.OFS_0,
ITF.MFGLTI_0,
ITF.TOTLTI_0,
ITF.MIC_0,
ITF.QUALTI_0,
ITF.PRPLTI_0

FROM ITMMASTER ITM
INNER JOIN ITMBPS ON ITMBPS.ITMREF_0 = ITM.ITMREF_0
INNER JOIN BPSUPPLIER BPS ON BPS.BPSNUM_0 = ITMBPS.BPSNUM_0
INNER JOIN ITMFACILIT ITF ON ITF.ITMREF_0 = ITM.ITMREF_0 and ITF.STOFCY_0 = 'AE1'
INNER JOIN ITMMVT ITV ON ITV.ITMREF_0 = ITM.ITMREF_0 and ITV.STOFCY_0 = ITF.STOFCY_0
INNER JOIN ITMCOST ITC ON ITC.STOFCY_0 = ITF.STOFCY_0 and ITC.ITMREF_0 = ITM.ITMREF_0 and GETDATE() >= ITC.ITCSTRDAT_0 and GETDATE() <= ITC.ITCENDDAT_0
